- name: Include variables.
  ansible.builtin.include_vars: "{{ vars }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: vars

- name: Install packages.
  ansible.builtin.package:
    name: "{{ package }}"
    state: present
  loop: "{{ ssh_packages }}"
  loop_control:
    loop_var: package
  notify: Restart sshd.

- name: Configure sshd.
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd.

- name: Start service.
  ansible.builtin.service:
    name: "{{ ssh_service }}"
    state: started
    enabled: true

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
