---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
      changed_when: false
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: true
      when: ansible_distribution == "Archlinux"
      changed_when: false
    - name: Wait for systemd initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        "running" in systemctl_status.stdout or
        "degraded" in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == "systemd"
      changed_when: false
      failed_when: systemctl_status.rc > 1
  tasks:
    - name: Include sshd role.
      ansible.builtin.include_role:
        name: "f_koehler.sshd"
